# Generated by Django 4.2.18 on 2025-02-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item_name', models.CharField(max_length=255)),
                ('sales', models.IntegerField()),
                ('current_stocks', models.IntegerField()),
            ],
        ),
    ]
