# Generated by Django 4.2.18 on 2025-02-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_salesdata_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdata',
            name='current_stocks',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='sales',
        ),
        migrations.AddField(
            model_name='salesdata',
            name='sold_qty',
            field=models.IntegerField(default=0),
        ),
    ]
