# Generated by Django 4.2.18 on 2025-02-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_salesdata_current_stocks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='item_id',
            field=models.TextField(max_length=10),
        ),
    ]
