# Generated by Django 4.2.18 on 2025-02-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_salesdata_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='item_id',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
