# Generated by Django 4.2.18 on 2025-03-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_salesdata_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('last_run', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
